export default {
    STORE_DEVICE_TOKEN: 'STORE_DEVICE_TOKEN',
    STORE_WIFI_CREDENTIALS: 'STORE_WIFI_CREDENTIALS',
    DEVICE_FINISHED_CONFIGURATION: 'DEVICE_FINISHED_CONFIGURATION',
    RESTART_CONFIGURATION: 'RESTART_CONFIGURATION',
}
