export default {
    UPDATE_REGISTERS: 'UPDATE_REGISTERS',
    STORE_DEVICES: 'STORE_DEVICES',
    SET_SELECTED_DEVICE: 'SET_SELECTED_DEVICE',
    SET_DEVICE_COLOR: 'SET_DEVICE_COLOR',
    SET_DEVICE_CODE: 'SET_DEVICE_CODE',
    START_UPDATE: 'START_UPDATE',
    REMOVE_UPDATE: 'REMOVE_UPDATE',
}
